-- CSE_Localisation
-- Author: lorna
-- DateCreated: 8/8/2019 11:09:58 PM
--------------------------------------------------------------

INSERT OR REPLACE INTO LocalizedText (Language, Tag, Text)
VALUES
	("pt_BR",	"LOC_CIVILIZATION_CSE_HASUPUWETERI_NAME",			"Hasupuweteri"	),
	("pt_BR",	"LOC_CIVILIZATION_CSE_HASUPUWETERI_ADJECTIVE",		"Hasupuweteri"	),
	("pt_BR",	"LOC_CIVILIZATION_CSE_HASUPUWETERI_DESCRIPTION",	"Cidade-estado de {LOC_CIVILIZATION_CSE_HASUPUWETERI_NAME}"		),
	("pt_BR",	"LOC_CSE_HASUPUWETERI_TRAIT_NAME",					"Bonus de Suzerano de {LOC_CIVILIZATION_CSE_HASUPUWETERI_NAME}"	),
	("pt_BR",	"LOC_CSE_HASUPUWETERI_TRAIT_DESCRIPTION",			"Seus construtores podem construir melhorias de Maloca.[NEWLINE][NEWLINE] Fornece +1 de [ICON_FOOD] Comida e +1 de [ICON_HOUSING] habitação no painel em que é construído com +1 de [ICON_FOOD] adicional com o Cívico Feudalismo. Painéis adjacentes não melhorados fornecem +1 de [ICON_FOOD] Comida. Concede +1 de [ICON_FOOD] Comida adicional para painéis adjacentes não melhorados e +1 de [ICON_CULTURE] Cultura para painéis adjacentes com alguma melhoria depois de pesquisar o Cívico Guildas. Deve ser construido em painéis de Floresta Tropical não adjacente a outra Maloca."	),

-- Após a primeira versão, tentar alterar para que fazendas recebam o tratamento de não melhorada	
--("pt_BR",	"LOC_CSE_HASUPUWETERI_TRAIT_DESCRIPTION",			"Seus construtores podem construir melhorias de Maloca.[NEWLINE][NEWLINE] Fornece +1 de [ICON_FOOD] Comida e +1 de [ICON_HOUSING] habitação no painel em que é construído com +1 de [ICON_FOOD] adicional com o Cívico Feudalismo. Painéis adjacentes não melhorados or com fazendas fornecem +1 de [ICON_FOOD] Comida. Concede +1 de [ICON_FOOD] Comida adicional para painéis adjacentes não melhorados ou com fazendas e +1 de [ICON_CULTURE] Cultura para painéis adjacentes com alguma melhoria, exceto fazendas, depois de pesquisar o Cívico Guildas. Deve ser construido em painéis de Floresta Tropical não adjacente a outra Maloca."	),

	("pt_BR",	"LOC_LEADER_MINOR_CIV_CSE_HASUPUWETERI_NAME",		"{LOC_CIVILIZATION_CSE_HASUPUWETERI_NAME}"	),
	("pt_BR",	"LOC_CITY_NAME_HASUPUWETERI",						"{LOC_CIVILIZATION_CSE_HASUPUWETERI_NAME}"	),

	("pt_BR",	"LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_CSE_HASUPUWETERI_CHAPTER_HISTORY_PARA_1",	"Hasupuweteri foi a aldeia Yanomami onde Kenneth Good foi designado por Napoleon Chagnon, autor do influente livro 'Yanomamö: The Fierce People', para comprovar a inveracidade da relação do índice protéico alimentar e a guerra dentro os Yanomami, mas acabou por comprovar a inveracidade do seu próprio livro. Hasupuweteri fora escolhida para Good por ele ser o mais robusto dentro seus alunos, considerando que de acordo com as afirmações de Chagnon, por não ter ainda sofrido contato com a sociedade externa, vivia em guerra intensa com seus vizinhos."	),
	("pt_BR",	"LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_CSE_HASUPUWETERI_CHAPTER_HISTORY_PARA_2",	"Entretanto, a realidade que Good experimentou na aldeia foi vastamente diferente daquela descrita pro Chagnon. O trabalho originalmente com duração de 12 meses se estendou por mais de dois anos. Good fora seduzido pela selva e pela cultura yanomami, deixando-se ficar por anos a fio entre os Hasupuweteri, inclusive apaixonando-se por uma moça yanomami. "	),
	("pt_BR",	"LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_CSE_HASUPUWETERI_CHAPTER_HISTORY_PARA_3",	"Good, na companhia de Carneiro, curador do Museu Americano de História Natural para América do Sul, subiu o Orenoco até a aldeia dos Hasupuweteri. Estes, atraídos pelo barulho do motor, esperavam os dois pesquisadores na margem do rio. O aspecto ameaçador que aparentavam à distância em função de suas pinturas, arcos e flechas dissipou-se logo. Quando os brancos se aproximaram, notaram que os Hasupuweteri eram só sorrisos e que nenhum deles apresentava um comportamento intimidador. Ao chegar à aldeia hasupuweteri, Good, inicialmente, armou sua cabana a 500 metros da aldeia. Após o primeiro mês de estadia entre eles, a imagem de “fierceness” passada por Chagnon se desvanecia e já se sentia à vontade para deixar de lado o gás paralisante e as latas de pó químico."	),
	("pt_BR",	"LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_CSE_HASUPUWETERI_CHAPTER_HISTORY_PARA_4",	"A primeira demonstração de “fierceness” presenciada por Good ocorreu no dia em que a equipe de combate à malária apareceu na aldeia para distribuir cloroquina aos Yanomami. No caminho para o rio, eles foram atacados por um grupo de curiosos que atiraram suas flechas e partiram, escondendo-se na mata. Um jovem foi ferido mortalmente por duas flechas. É a partir deste episódio que Good irá descobrir que as guerras entre aldeias descritas por Chagnon não passavam de ataques sorrateiros desferidos contra grupos pequenos que se esgueiravam pela selva. Eram flechas atiradas traiçoeiramente por um grupo pequeno que fugia correndo pela selva. As demonstrações de violência existiam, porém se davam na maior parte das vezes de forma ritualizada, visando assim manter a solidariedade grupal. Este fato levou-o a compreender que as afirmações de Chagnon eram descontextualizadas e sensacionalistas "	),
	("pt_BR",	"LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_CSE_HASUPUWETERI_CHAPTER_HISTORY_PARA_5",	"Depois de algum tempo, Good decidiu transferir-se para a casa coletiva, onde poderia observar melhor os Yanomami. Em sua primeira noite na maloca, o fantasma da violência descrita por Chagnon ainda o aterrorizou: os gritos que cortavam a noite e o vulto das pessoas sob a luz do luar fizeram com que o medo tomasse conta de sua vigília. Mas suas preocupações logo se revelaram infundadas. A violência, expressão instintiva e sem amarras sociais na ótica de Chagnon, será descrita como um comportamento em grande parte ritualizado: insultos e queixas públicas, apresentados diante de toda a comunidade, preservariam a solidariedade do grupo."),
	("pt_BR",	"LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_CSE_HASUPUWETERI_CHAPTER_HISTORY_PARA_6",	"Durante seus estudos Good fora se afeiçoando a uma Yanomami chamada Iarima. Inicialmente como um gracejo com respaldo cultural, depois como uma forma de se integrar a tribo e finalmente como uma completa afeição. Este relacionamento fez com que Good passasse muito mais tempo que o necessário para um estudo da aldeia, utilizando quaiquer que fossem as desculpas ou motivos para retornar. Após diversos percalços, ele retorna aos Estados Unidos casado com Iarima e seu irmão e publica o livro contando a história de seu romance, apesar que a história ainda não haveria terminado. Após a publicação do livro, uma reportagem de tv informou o mundo que Iarima decidira voltar definitivamente para os Yanomami, deixando marido e filhos em Nova Jersey."),
	
	("pt_BR",	"LOC_IMPROVEMENT_CSE_MALOCA_NAME",					"Maloca"	),
	("pt_BR",	"LOC_IMPROVEMENT_CSE_MALOCA_DESCRIPTION",			"Seus construtores podem construir melhorias de Maloca.[NEWLINE][NEWLINE] Fornece +1 de [ICON_FOOD] Comida e +1 de [ICON_HOUSING] habitação no painel em que é construído com +1 de [ICON_FOOD] adicional com o Cívico Feudalismo. Painéis adjacentes não melhorados fornecem +1 de [ICON_FOOD] Comida. Concede +1 de [ICON_FOOD] Comida adicional para painéis adjacentes não melhorados e +1 de [ICON_CULTURE] Cultura para painéis adjacentes com alguma melhoria depois de pesquisar o Cívico Guildas. Deve ser construido em painéis de Floresta Tropical não adjacente a outra Maloca."	),

	("pt_BR",	"LOC_PEDIA_IMPROVEMENTS_PAGE_IMPROVEMENT_CSE_MALOCA_CHAPTER_HISTORY_PARA_1",		"Apesar de muito utilizado como um termo depreciativo para casas improvisadas ou de materiais de baixa qualidade, o termo Maloca é utilizado pelos indígenas brasileiros para descrever casas comunais que abrigavam diversas famílias. O termo faz contrapartica com a oca, que é a casa da família individual."	);
	("pt_BR",	"LOC_PEDIA_IMPROVEMENTS_PAGE_IMPROVEMENT_CSE_MALOCA_CHAPTER_HISTORY_PARA_2",		"As técnicas construtivas, matérias aplicados e adaptações ao meio fazem parte do contexto de cada região étnica. Geralmente as técnicas e materiais empregados se assemelham entre as diversas tribos. O que difere são algumas formas aplicadas e a adaptação que a tecnologia sofreu em relação a região climática. Os materiais utilizados destacam-se a madeira, folhas e fibras. Uma técnica muito comum, é o sistema de amarrações, que é um conjunto de procedimento técnico de fixação de diferentes elementos construtivos, de estrutra ou revestimento entrelaçando as peças de madeira com cipó. Os sistemas de encaixe são bastante utilizados na arquitetura, onde existe o encaixe lateral, que são paus ligeiramente escavados para obtenção de melhor ajustamento e o encaixe de topo, quando uma peça horizontal é fixada acima de outra vertical. As diferentes técnicas podem ser usadas ao mesmo tempo."	);
	("pt_BR",	"LOC_PEDIA_IMPROVEMENTS_PAGE_IMPROVEMENT_CSE_MALOCA_CHAPTER_HISTORY_PARA_3",		"Para os Yanomami, a área utilizada em torno da Maloca é normalmente dividida em círculos concêntricos de diferentes raios. O primeiro círculo, num raio de cinco quilômetros, circunscreve a área de uso imediato da comunidade: pequena coleta feminina, pesca individual ou, no verão, pesca coletiva com timbó, caça ocasional de curta duração (ao amanhecer ou ao entardecer) e atividades agrícolas. O segundo círculo, num raio de cinco a dez quilômetros, é a área de caça individual (rama huu) e da coleta familiar do dia-a-dia."	);
	("pt_BR",	"LOC_PEDIA_IMPROVEMENTS_PAGE_IMPROVEMENT_CSE_MALOCA_CHAPTER_HISTORY_PARA_4",		"O terceiro círculo, num raio de dez a vinte quilômetros, é a área das expedições de caça coletivas (henimou) de uma a duas semanas que antecedem os rituais funerários (cremações dos ossos, enterros ou ingestões de cinzas nas cerimônias intercomunitárias reahu), bem como das longas expedições plurifamiliares de coleta e caça (três a seis semanas) durante a fase de maturação das novas roças (waima huu). Encontram-se também nesse \"terceiro círculo\" tanto as roças novas quanto as antigas, junto às quais se acampa esporadicamente – para cultivar nas primeiras, colher nas segundas – e em cujos arredores a caça é abundante."	);
	
--