-- CSE_Localisation
-- Author: lorna
-- DateCreated: 8/8/2019 11:09:58 PM
--------------------------------------------------------------

INSERT OR REPLACE INTO LocalizedText (Language, Tag, Text)
VALUES
	("en_US",	"LOC_CIVILIZATION_CSE_HASUPUWETERI_NAME",			"Hasupuweteri"	),
	("en_US",	"LOC_CIVILIZATION_CSE_HASUPUWETERI_ADJECTIVE",		"Hasupuweterian"	),
	("en_US",	"LOC_CIVILIZATION_CSE_HASUPUWETERI_DESCRIPTION",	"{LOC_CIVILIZATION_CSE_HASUPUWETERI_NAME} city-state"		),
	("en_US",	"LOC_CSE_HASUPUWETERI_TRAIT_NAME",					"{LOC_CIVILIZATION_CSE_HASUPUWETERI_NAME} Suzerain Bonus"	),
	("en_US",	"LOC_CSE_HASUPUWETERI_TRAIT_DESCRIPTION",			"Your builders may construct Maloca improvements.[NEWLINE][NEWLINE] Yields +1 [ICON_FOOD] Food and grants +1 [ICON_HOUSING] Housing in its tile with an additional +1 [ICON_FOOD] Food with the Feudalism Civic. Each unimproved adjacent tile yields +1 [ICON_FOOD] Food. Grants an additional +1 [ICON_FOOD] Food to unimproved adjacent tiles and +1 [ICON_CULTURE] Culture to improved adjacent tiles with the Guilds Civic."	),

--	("en_US",	"LOC_CSE_HASUPUWETERI_TRAIT_DESCRIPTION",			"Your builders may construct Maloca improvements.[NEWLINE][NEWLINE] Yields +1 [ICON_FOOD] Food and grants +1 [ICON_HOUSING] Housing in its tile with an additional +1 Food with the Feudalism Civic. Each unimproved adjacent or farm tile yields +1 [ICON_FOOD] Food. Grants an additional +1 [ICON_FOOD] Food to unimproved adjacent or farm tiles and +1 [ICON_CULTURE] Culture to improved adjacent tiles, except for farms, with the Guilds Civic."	),

	("en_US",	"LOC_LEADER_MINOR_CIV_CSE_HASUPUWETERI_NAME",		"{LOC_CIVILIZATION_CSE_HASUPUWETERI_NAME}"	),
	("en_US",	"LOC_CITY_NAME_HASUPUWETERI",						"{LOC_CIVILIZATION_CSE_HASUPUWETERI_NAME}"	),

	("en_US",	"LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_CSE_HASUPUWETERI_CHAPTER_HISTORY_PARA_1",	"Hasupuweteri was the Yanomami village where Kenneth Good was appointed by Napoleon Chagnon, author of the influential book 'Yanomamö: The Fierce People', to prove the unreliability of the food protein index and the war within the Yanomami, but ultimately proved the untruth of his own book. Hasupuweteri had been chosen for Good because he was the most robust within his students, considering that according to Chagnon's assertions, because Hasupuweteri had not yet been in contact with outside society, it lived in intense war with his neighbors."	),
	("en_US",	"LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_CSE_HASUPUWETERI_CHAPTER_HISTORY_PARA_2",	"However, the reality Good experienced in the village was vastly different from that described for Chagnon. The work originally lasting 12 months extended over two years. Good had been seduced by the jungle and Yanomami culture, letting himself be for years among the Hasupuweteri, including falling in love with a Yanomami girl."	),
	("en_US",	"LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_CSE_HASUPUWETERI_CHAPTER_HISTORY_PARA_3",	"Good, accompanied by Carneiro, curator of the American Museum of Natural History for South America, climbed the Orinoco to the Hasupuweteri village. These, attracted by the noise of the engine, were waiting for the two researchers on the river bank. The menacing aspect they seemed at a distance from their paintings, bows, and arrows soon dissipated. As the whites approached, they noticed that the Hasupuweteri were just smiles and none of them behaved intimidatingly. Arriving at Hasupuweteri Village, Good initially pitched his hut within 500 meters of the village. After the first month of their stay, Chagnon's image of 'fierceness' faded away and he was comfortable to set aside the paralyzing gas and cans of chemical dust."	),
	("en_US",	"LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_CSE_HASUPUWETERI_CHAPTER_HISTORY_PARA_4",	"Good first witnessed demonstration of fierceness was on the day the malaria team came to the village to distribute chloroquine to the Yanomami. On the way to the river, they were attacked by a group of onlookers who shot their arrows and departed, hiding in the woods. One young man was mortally wounded by two arrows. It is from this episode that Good will discover that the village wars described by Chagnon were nothing more than sneaky attacks on small groups sneaking through the jungle. They were arrows shot treacherously by a small group running away through the jungle. Demonstrations of violence existed, but were mostly ritualized, in order to maintain group solidarity. This fact led him to understand that Chagnon's statements were out of context and sensational."	),
	("en_US",	"LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_CSE_HASUPUWETERI_CHAPTER_HISTORY_PARA_5",	"After a while, Good decided to move to the collective house, where he could better observe the Yanomami. On his first night in the maloca, the ghost of violence described by Chagnon still terrified him: the screams that cut through the night and the bulk of the people in the moonlight made fear take over his vigil. But their concerns soon proved unfounded. The violence, in Chagnon's view described as an instinctive expression with no social strings attached, will be described by Good as a largely ritualized behavior: insults and public grievances, presented to the whole community, would preserve the group's solidarity."	),
	("en_US",	"LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_CSE_HASUPUWETERI_CHAPTER_HISTORY_PARA_6",	"During his studies Good had become fond of a Yanomami named Iarima. Initially as a culturally backed joke, then as a way of integrate with the tribe and finally as a complete affection. This relationship made Good spend much more time than necessary for a village study, using whatever excuses or reasons for returning. After several mishaps, he returns to the United States married to Iarima along with her brother and publishes the book telling the story of his novel, although the story would not be over yet. After the book was published, a TV report informed the world that Iarima had decided to return permanently to the Yanomami, leaving her husband and children in New Jersey."	),

	("en_US",	"LOC_IMPROVEMENT_CSE_MALOCA_NAME",					"Maloca"	),
	("en_US",	"LOC_IMPROVEMENT_CSE_MALOCA_DESCRIPTION",			"Yields +1 [ICON_FOOD] Food and grants +1 [ICON_HOUSING] Housing in its tile with an additional +1 [ICON_FOOD] Food with the Feudalism Civic. Each unimproved adjacent tile yields +1 [ICON_FOOD] Food. Grants an additional +1 [ICON_FOOD] Food to unimproved adjacent tiles and +1 [ICON_CULTURE] Culture to improved adjacent tiles with the Guilds Civic."	),

	("en_US",	"LOC_PEDIA_IMPROVEMENTS_PAGE_IMPROVEMENT_CSE_DAGOBA_CHAPTER_HISTORY_PARA_1",		"Although widely used as a derogatory term for makeshift homes or low quality materials, the term Maloca is used by Brazilian Indians to describe communal houses that housed several families. The term is counterpart to the 'oca', which is the home of the individual family."	),
	("en_US",	"LOC_PEDIA_IMPROVEMENTS_PAGE_IMPROVEMENT_CSE_DAGOBA_CHAPTER_HISTORY_PARA_2",		"Constructive techniques, applied materials and environmental adaptations are part of the context of each ethnic region. Generally the techniques and materials employed are similar among the various tribes. What differs are some forms applied and the adaptation that technology has suffered in relation to the climate region. The materials used include wood, leaves and fibers. A very common technique is the lashing system, which is a set of technical procedure of fixing different constructive elements, structure or cladding interlacing wood pieces with liana. Attachment systems are widely used in architecture, where there is the lateral fit, which are slightly dug sticks for better fit and the top fit when a horizontal piece is fixed above another vertical. The different techniques can be used at the same time."	),
	("en_US",	"LOC_PEDIA_IMPROVEMENTS_PAGE_IMPROVEMENT_CSE_DAGOBA_CHAPTER_HISTORY_PARA_3",		"For the Yanomami, the area used around the Maloca is usually divided into concentric circles of different radii. The first circle, within a radius of about 3 miles (5 km), circumscribes the area of immediate use of the community: small female collection, individual fishing or, in summer, collective fishing with timbó, occasional short-term hunting (dawn or dusk) and agricultural activities . The second circle, within a radius of 3 to 6 miles (5 to 10 km), is the area for individual hunting (rama huu) and day-to-day family gathering."	),
	("en_US",	"LOC_PEDIA_IMPROVEMENTS_PAGE_IMPROVEMENT_CSE_DAGOBA_CHAPTER_HISTORY_PARA_4",		"The third circle, within a radius of 6 to 12 miles (10 to 20 km), is the area of one to two-week henimou collective hunting expeditions that precede the funeral rituals (bone cremations, burials, or ash intakes at the reahu intercommunity ceremonies) as well as long multi-family collection and hunting expeditions (three to six weeks) during the maturation phase of the new fields (waima huu). There are also in this \"third circle\" both the new and the old fields, along which they sporadically camp - to cultivate in the former, to harvest in the latter - and in whose surroundings hunting is abundant."	);	