-- CSE_Localisation
-- Author: lorna
-- DateCreated: 8/8/2019 11:09:58 PM
--------------------------------------------------------------

	("en_US",	"LOC_CIVILIZATION_CSE_ANURADHAPURA_NAME",			"Anuradhapura"	),
	("en_US",	"LOC_CIVILIZATION_CSE_ANURADHAPURA_ADJECTIVE",		"Anuradhian"	),
	("en_US",	"LOC_CIVILIZATION_CSE_ANURADHAPURA_DESCRIPTION",	"{LOC_CIVILIZATION_CSE_ANURADHAPURA_NAME} city-state"		),
	("en_US",	"LOC_CSE_ANURADHAPURA_TRAIT_NAME",					"{LOC_CIVILIZATION_CSE_ANURADHAPURA_NAME} Suzerain Bonus"	),
	("en_US",	"LOC_CSE_ANURADHAPURA_TRAIT_DESCRIPTION",			"Your builders may construct Dagoba improvements.[NEWLINE][NEWLINE] Dagobas yield +1 [ICON_SCIENCE] Science and +1 [ICON_FAITH] Faith, with additional +1 [ICON_SCIENCE] Science for each adjacent Campus, and +1 [ICON_FAITH] Faith for every adjacent Holy Site. Additional [ICON_SCIENCE] Science and [ICON_FAITH] Faith as you advance through the Civics and Technology trees."	),

	("en_US",	"LOC_LEADER_MINOR_CIV_CSE_ANURADHAPURA_NAME",		"{LOC_CIVILIZATION_CSE_ANURADHAPURA_NAME}"	),
	("en_US",	"LOC_CITY_NAME_ANURADHAPURA",						"{LOC_CIVILIZATION_CSE_ANURADHAPURA_NAME}"	),

	("en_US",	"LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_CSE_ANURADHAPURA_CHAPTER_HISTORY_PARA_1",	"Anuradhapura is one of the ancient capitals of Sri Lanka, famous for its well-preserved ruins of an ancient Sri Lankan civilization. It was the third capital of the Kingdom of Rajarata, following the kingdoms of Tambapanni and Upatissa Nuwara. It is believed that King Pandukabhaya made it his capital in the 4th century BC, and that he also laid out the town and its suburbs according to a well-organized plan. He constructed a reservoir named Abhayavapi. He established shrines for yakkhas such as Kalawela and Cittaraja. He housed the Yaksini-Cetiya in the form of a mare within the royal precincts, and offerings were made to all these demi-gods every year. He chose the sites for the cemetery and for the place of execution, the Chapel of the Western Queen, the Pacchimarajini, the Vessavana Banyan Tree, the Palm of the Vyadhadeva, the Yona Quarter and the House of the Great Sacrifice. The slaves or Candalas were assigned their duties, and a village was set apart for them."	),
	("en_US",	"LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_CSE_ANURADHAPURA_CHAPTER_HISTORY_PARA_2",	"With the introduction of Buddhism, the city gained more prominence and the great building era began. The Mahavansa states that King Kutakannatissa built the first city wall to a height of seven cubits with a moat in front of the wall. This fortification was further enlarged by raising the wall a further 11 cubits to 18 cubits by King Vasabha. The king also added fortified gatehouses at the entrances of which the ruins can be seen to date. The Mahavamsa also states that soothsayers and architects were consulted in the construction. The city's popularity grew both as a ritual centre and as the administrative centre, a large population was attracted to the city for permanent settlement. Thus the living facilities were improved to accommodate the expanding population. King Vasabha constructed many ponds which were fed by a network of subterranean channels which were constructed to supply water to the city. The Tissa and Abhayavapi tanks were built, the Nuwara weva was built and the Malwatu Oya was dammed to build the Nachchaduwa wewa which was 4,408 acres (17.84 km2) in size."	),
	("en_US",	"LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_CSE_ANURADHAPURA_CHAPTER_HISTORY_PARA_3",	"Parks were also provided in the city. The Ranmasu Uyana below the bund of Tissavapi or Tissa weva was one such, but it was strictly reserved for the members of the royal family. Health care and education were two other aspects to which the authorities paid attention. There were several hospitals in the city. In the 4th century King Upatissa II provided quarters and homes for the crippled and the blind. King Buddhadasa (337-365 AD), himself a doctor of great repute, appointed a physician to be in charge of every ten villages. For the maintenance of these doctors, one tenth of the income from the fields was set apart. He also set up refuges for the sick in every village. Doctors were also appointed to look after the animals. Kassapa V (914-923 AD) founded a hospital close to the southern gate of Anuradhapura. General Sena in the 10th century is believed to have built a hospital close to the ceremonial street (Managala Veediya). The history of medical care began early, for in the 4th century BC King Pandukhabaya, in the course of sanitizing the town constructed a hospital. A large workforce was entrusted with the task of keeping the city clean."	),
	("en_US",	"LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_CSE_ANURADHAPURA_CHAPTER_HISTORY_PARA_4",	"Anuradhapura attained its highest magnificence about the commencement of the common era. The city had some of the most complex irrigation systems of the ancient world, situated in the dry zone of the country the administration built many tanks to irrigate the land. Most of these tanks still survive. The area was uninhabited for many centuries, but the local population remained aware of the ruins. In Robert Knox's 1681 An Historical Relation of the Island Ceylon, he wrote: 'At this City of Anurodgburro is a Watch kept, beyond which are no more people that yield obedience to the King of Candy'. In 1821, John Davy wrote that: 'Anooradapoora, so long the capital of Ceylon, is now a small mean village, in the midst of a desert. A large tank, numerous stone pillars, two or three immense tumuli, (probably old dagobahs,) are its principal remains. It is still considered a sacred spot; and is a place of pilgrimage'."	),

	("en_US",	"LOC_IMPROVEMENT_CSE_DAGOBA_NAME",					"Dagoba"	),
	("en_US",	"LOC_IMPROVEMENT_CSE_DAGOBA_DESCRIPTION",			"Unlocks the Builder ability to construct a Dagoba.[NEWLINE][NEWLINE]Yields +1 [ICON_SCIENCE] Science and +1 [ICON_FAITH] Faith, with additional +1 [ICON_SCIENCE] Science for each adjacent Campus, and +1 [ICON_FAITH] Faith for every adjacent Holy Site. Additional [ICON_SCIENCE] Science and [ICON_FAITH] Faith as you advance through the Civics and Technology trees."	),

	("en_US",	"LOC_PEDIA_IMPROVEMENTS_PAGE_IMPROVEMENT_CSE_DAGOBA_CHAPTER_HISTORY_PARA_1",		"Stupas, 'Dagobas' in Sinhalese, originated as pre-Buddhist tumuli in which sramanas were buried in a seated position called cetiya. After the parinirvana of the Buddha, his remains were cremated and the ashes divided and buried under eight mounds with two further mounds encasing the urn and the embers. The stupa was elaborated as Buddhism spread to other Asian countries, becoming, for example, the chörten of Tibet and the pagoda in East Asia. Stupas were built in Sri Lanka soon after Devanampiya Tissa of Anuradhapura converted to Buddhism. The first stupa to be built was the Thuparamaya. Later, many more were built over the years, some like the Jetavanaramaya in Anuradhapura being one of the tallest ancient structures in the world."	);